### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [intel/numatop#15]
Would you like to add more error handling for return values from functions like the following?
- [pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html) ⇒ [perf_handler](https://github.com/01org/numatop/blob/3f8ee7ab1c96d70f8e2ecda5e188b7b4eeb051c9/common/perf.c#L174)
- [pthread_mutex_lock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html) ⇒ [cpu_profiling_smpl](https://github.com/01org/numatop/blob/3f8ee7ab1c96d70f8e2ecda5e188b7b4eeb051c9/common/os/os_perf.c#L193)

**Comment by yaoj** [comment]
Sure, thanks! I will add more error handling in next version.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software? :thinking:
