### ISSUE TITLE
NumaTOP failed to start

### ISSUE THREAD

**Issue by hghorayeb** [intel/numatop#19]
Hello,

I am using the last version of numatop code, i successfully run make install. however i am facing a blocking issue to start numatop. here below the details:

Please note that I didn't apply the kernel patch  you mentioned. I didn't succeed to apply it, maybe a hint on the linux command to apply this patch could help.

bash$ numatop
NumaTOP is starting ...
Fail to setup perf (probably permission denied)!

with root:
bash$ numatop
NumaTOP is starting ...
Segmentation fault (core dumped)
ibm001srv root /nfshome/nonuser/autoengine/

Operating Environment:
bash$ uname -a
Linux ibm001srv 4.5.4-1.el7.elrepo.x86_64 #1 SMP Thu May 12 12:17:54 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

bash$ which numatop
/usr/local/bin/numatop
ibm001srv autoengine ~/
bash$ ls -l /usr/local/bin/numatop
-rwxr-xr-x. 1 root root 541174 May 16 17:07 /usr/local/bin/numatop*

bash$ cat /proc/cpuinfo | grep 'model name' | uniq
model name      : Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz

**Comment by yaoj** [comment]
Please remove the top patch “2327110 Add cache monitoring and memory bandwidth monitoring features”, because it strongly relies on the kernel patch (CQM/MBM patch) which I mentioned. If you didn’t apply the kernel patch, there  would be the issue.

I will provide a patch some time later for getting better compatibility on the kernel which is not applied with the required CQM/MBM kernel patch.

Thanks
Jin Yao

**Comment by hghorayeb** [comment]
I removed the patch:

bash$ git fetch origin 92cbe59ff3abc74356801b471b281f03443a3e23
From https://github.com/01org/numatop
 * branch            92cbe59ff3abc74356801b471b281f03443a3e23 -> FETCH_HEAD

and successfully built the numatop:
bash$ make
gcc -g -Wall -O2 -o cmd.o -c common/cmd.c
gcc -g -Wall -O2 -o disp.o -c common/disp.c
gcc -g -Wall -O2 -o lwp.o -c common/lwp.c
gcc -g -Wall -O2 -o numatop.o -c common/numatop.c
gcc -g -Wall -O2 -o page.o -c common/page.c
gcc -g -Wall -O2 -o perf.o -c common/perf.c
gcc -g -Wall -O2 -o proc.o -c common/proc.c
gcc -g -Wall -O2 -o reg.o -c common/reg.c
gcc -g -Wall -O2 -o util.o -c common/util.c
gcc -g -Wall -O2 -o win.o -c common/win.c
gcc -g -Wall -O2 -o os_cmd.o -c common/os/os_cmd.c
gcc -g -Wall -O2 -o os_perf.o -c common/os/os_perf.c
gcc -g -Wall -O2 -o os_win.o -c common/os/os_win.c
gcc -g -Wall -O2 -o node.o -c common/os/node.c
gcc -g -Wall -O2 -o map.o -c common/os/map.c
gcc -g -Wall -O2 -o os_util.o -c common/os/os_util.c
gcc -g -Wall -O2 -o plat.o -c common/os/plat.c
gcc -g -Wall -O2 -o pfwrapper.o -c common/os/pfwrapper.c
gcc -g -Wall -O2 -o sym.o -c common/os/sym.c
gcc -g -Wall -O2 -o os_page.o -c common/os/os_page.c
gcc -g -Wall -O2 -o wsm.o -c intel/wsm.c
gcc -g -Wall -O2 -o snb.o -c intel/snb.c
gcc -g -Wall -O2 -o nhm.o -c intel/nhm.c
gcc -g -Wall -O2 -o bdw.o -c intel/bdw.c
gcc -g -o numatop cmd.o disp.o lwp.o numatop.o page.o perf.o proc.o reg.o util.o                                                                                              win.o os_cmd.o os_perf.o os_win.o node.o map.o os_util.o plat.o pfwrapper.o sym                                                                                             .o os_page.o wsm.o snb.o nhm.o bdw.o -lncurses -lpthread -lnuma

however, I still have the issue:

bash$ ./numatop
NumaTOP is starting ...
Fail to setup perf (probably permission denied)!

**Comment by yaoj** [comment]
You have to run numatop by root.

**Comment by hghorayeb** [comment]
With the root there is a core dumped:

ibm001srv root /nfshome/nonuser/autoengine/
bash$ numatop
NumaTOP is starting ...
Segmentation fault (core dumped)

**Comment by yaoj** [comment]
No issue occurred at my side. Could you send me with the core file in another mail thread?
yao.jin@intel.com<mailto:yao.jin@intel.com>

Thanks
Jin Yao
