### ISSUE TITLE
numatop comapitability

### ISSUE THREAD

**Issue by saurin2** [intel/numatop#24]
Hi, We have following system, microcode version is 0x2e, documents says CPU microcode
version 0x618 or 0x70c or later is required. want to make sure that numatop will work on this system or not.

cat /proc/cpuinfo 
.........
model name	: Intel Xeon CPU E5-4648 v3  1.70GHz
microcode	: 0x2e
.........

**Comment by yaoj** [comment]
That should be OK.

**Comment by saurin2** [comment]
Thanks Jin
