### ISSUE TITLE
Support for Haswell?

### ISSUE THREAD

**Issue by simar7** [intel/numatop#6]
Sorry if this has been already discussed or is known but I'm looking to run numatop on a Haswell machine and was wondering if the Haswell architecture specific code is in the works? Will it be ever made public? Thanks!

**Comment by simar7** [comment]
@yaoj does [this](https://github.com/01org/numatop/commit/f1a317da5a98219932d43c9848438983ff8cd55d) patch take care of everything haswell?

**Comment by aultj** [comment]
Does numatop support Broadwell?

**Comment by yaoj** [comment]
Yes, it supports but please use the upstream kernel (e.g. 4.6). Because some performance counters are only supported in latest kernel.
